<?php

return [
    'key_code' => [
        'category',
        'category_list',
        'category_add',
        'category_edit',
        'category_delete',
        'product',
        'product_list',
        'product_add',
        'product_edit',
        'product_delete',
        'order',
        'order_list',
        'order_status',
        'order_detail',
        'order_cancel',
        'order_delete',
        'member',
        'member_list',
        'member_add',
        'member_edit',
        'member_delete',
        'role',
        'role_list',
        'role_add',
        'role_edit',
        'role_delete',
        'permission',
        'permission_list',
        'permission_add',
        'permission_edit',
        'permission_delete',
    ]
];
